apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-7ham
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-7ham
    app.kubernetes.io/part-of: tkrw-pr712-0075-0027-app
  name: devfile-sample-7ham
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-7ham
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-7ham
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-7ham@sha256:e541a1c0aef84ae5a1fb76f77b5565031e2609730c6a9f707e64c296219b6110
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
