apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-7ham
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0027-tenant/tkrw-pr712-0075-0027-app/devfile-sample-7ham@sha256:e541a1c0aef84ae5a1fb76f77b5565031e2609730c6a9f707e64c296219b6110
        name: my-nodejs
        resources: {}
status: {}
